### ISSUE TITLE
wiki improvements

### ISSUE THREAD

**Issue by Kebap** [demonnic/muddler#12]
https://github.com/demonnic/muddler/wiki/Keycodes
- This means that in order to bind to, say, a capital K but shift+k.
  - "but" should be "put"

**Comment by Kebap** [comment]
https://github.com/demonnic/muddler/wiki
- should mention all possible subdirectory names. Currently mentions aliases, ressources, scripts and timers, but not triggers and keys (or keybindings?) - instead proceeds to take a look at an example, but that doesn't contain all of those items either. Should first list possiblities, only after review an example. Instead, comes back to describe generic folder descriptions and contents of ressources after example, mixing description and example. Found out about triggers item by looking at other example included in source but not in wiki. Found out about keys via trial & error plus reviewing groovy source. Should be easier.

**Comment by Kebap** [comment]
https://github.com/demonnic/muddler/wiki/Keybindings
- Comments in keys.json mention "alias" a few times, but should be "keys"
  - "the name of the alias object being created"
  - "Same as typing in the command field in the alias editor"

**Comment by Kebap** [comment]
https://github.com/demonnic/muddler/wiki/Keycodes
- Section "other named keys" should list all named keys
  - avoid making readers scan all contents above to find e.g. "plus" which is not in list below
  - there is no "minus" mentioned anywhere either
  - what about the other keypad mathmatical keys? Mudlet calls them "slash" and "asterisk" - will muddler recognize those, too?

**Comment by Kebap** [comment]
https://github.com/demonnic/muddler/wiki
- Section "Configuration" needs additional options added from release 0.6 https://github.com/demonnic/muddler/releases/tag/0.6

**Comment by demonnic** [comment]
Thank you, I will try to make some adjustments to the wiki tonight/this weekend and let you know. Appreciate the feedback.

**Comment by demonnic** [comment]
I have just pushed some updates to the wiki which I believe cover your feedback. Take a look and let me know?

**Comment by Kebap** [comment]
Thanks for the improvements! I noticed some omissions still:

https://github.com/demonnic/muddler/wiki/Keycodes
* Section "other named keys" should be renamed to "named keys" and include "plus"
  * avoid making readers scan all contents above to find "plus" which is not in list below

https://github.com/demonnic/muddler/wiki
* Section "Configuration" does not yet mention "description" key and/or relation to README.md at all


New:

https://github.com/demonnic/muddler/wiki/Aliases
* Should use "Json" syntax highlighting just like the other wiki sub-pages do

**Comment by demonnic** [comment]
Have another look, please

**Comment by Kebap** [comment]
You improved all I mentioned. Thanks!

**Comment by Kebap** [comment]
https://github.com/demonnic/muddler/wiki/Triggers

Should mention default state for "highlight" option, I guess it's "no" but most others state theirs explicitly, this doesn't

**Comment by demonnic** [comment]
handled
