### ISSUE TITLE
How can I add details to folders?

### ISSUE THREAD

**Issue by Kebap** [demonnic/muddler#13]
In Mudlet, for some reason, you can add most all things and details to a folder, that you can to an item (be it alias, trigger, key, etc) - but how to do the same in muddle?

For example, I have a folder of aliases and in the folder itself, I have put a lua comment as code to explain in more detail, which kind of aliases are contained.

Not sure how to muddle. Am I missing something here?

**Comment by demonnic** [comment]
Right now there's not really an easy way to do this. I simply moved away from using the folders to hold things. That being said I'm not against it and have kicked around a couple ideas on how to add it.
