### ISSUE TITLE
Template repository

### ISSUE THREAD

**Issue by vadi2** [demonnic/muddler#24]
It would really help muddler out if there was a template repository that's already setup with the right project structure and CI plugged in ([example](https://github.com/filipdutescu/modern-cpp-template)). That way someone can just click a button and whole lot of boilerplate work is done for them!

**Comment by demonnic** [comment]
hmmm, I'd been kicking around the idea of a `muddle init` command which would ask a couple of questions and generate your mfile and a basic file structure based on your answers

```
muddle init
What is your package name? MDK
Short description? A collection of stuff
What version do you want to start at [1.0.0]? 1.0.0
Create gitignore file [Y/n]? Y
```

And have it generate everything based on the information you've given it. But I could see how a template repo you could clone and start changing stuff in could be a good route.

**Comment by Kebap** [comment]
Was this done by https://github.com/demonnic/muddler/releases/tag/0.13 ?

**Comment by demonnic** [comment]
Mostly, actually... I missed the part about setting up ci and may do a .14 release to add that in.

**Comment by demonnic** [comment]
@vadi2 do you reckon the project generation built into muddler now suffices for this, or should I spin up an actual repository for people to clone from do you think?

**Comment by vadi2** [comment]
The init command is fine, though it's not visible anywhere on https://github.com/demonnic/muddler so chances are it'll get missed by someone new. With that improved, it'll work.
