### ISSUE TITLE
Request: allow for an alternative to @PKGNAME@ which is a valid lua identifier

### ISSUE THREAD

**Issue by wbk** [demonnic/muddler#28]
### Use case

I've been using `@PKGNAME@` as a prefix to namespace any globals I create, but because `@` symbols are not valid inside of lua identifiers, this does not sit well with the language server in vscode:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/978231/193299918-43b63475-4ef8-4d72-ba08-02ed9d82d71d.png">

I suggest an alternative syntax allowing double-underscores (`__`) to replace the `@` symbols anywhere this global search and replace happens, so that

`__PKGNAME__` is equivalent to `@PKGNAME@`; and such that if my package is named `Foo`, then  `__PKGNAME___bar` will transpile to `Foo_bar` within generated mudlet lua scripts.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/978231/193300494-d6d17ad9-93db-4b9a-a75b-2f20155e6ce6.png">

**Comment by demonnic** [comment]
In new 1.0.0 release =)
