### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by Kebap** [demonnic/muddler#33]
Muddler [said](https://github.com/MorgenGrauen/mg-mudlet/actions/runs/4097872382/jobs/7066563463):
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by demonnic** [comment]
hmm, build-with-muddler doesn't use either of those actions internally, I think it's saying you should update those specific actions (checkout and upload-artifact) in your workflow.

I went ahead and updated the example in the readme with the latest versions of checkout and upload-artifact at this time, but the build-with-muddler action itself should be good. It's really just a few bash scripts =)
