### ISSUE TITLE
wiki examples got superfluous ]

### ISSUE THREAD

**Issue by Kebap** [demonnic/muddler#7]
Alias:
![image](https://user-images.githubusercontent.com/117238/84576783-a78ede80-adb7-11ea-85c3-ffed2c7927dd.png)

Keys:
![image](https://user-images.githubusercontent.com/117238/84576818-c42b1680-adb7-11ea-8e32-21cbbb4340f4.png)

Scripts:
![image](https://user-images.githubusercontent.com/117238/84576830-dad16d80-adb7-11ea-9a9d-d6dd54c770f5.png)

Timers:
![image](https://user-images.githubusercontent.com/117238/84576839-f50b4b80-adb7-11ea-9ef7-b9de28fd6383.png)

Triggers:
![image](https://user-images.githubusercontent.com/117238/84576876-2edc5200-adb8-11ea-8e62-3ed0fe6ef694.png)

**Comment by demonnic** [comment]
good catch, not sure how that happened honestly. Will go through and edit the pages shortly

**Comment by demonnic** [comment]
Updated, believe I caught them all. Must have been a copypasta issue.

**Comment by Kebap** [comment]
Nice, thanks!
